info:
  contact: {}
paths:
  /health/liveness:
    get:
      description: Check if the service is alive
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check if the service is alive
  /health/readiness:
    get:
      description: Check if the service is ready
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check if the service is ready
swagger: "2.0"
